org: serverlesscloud
app: multi-cloud-benchmark
service: aws-java8
provider:
  name: aws
  runtime: java-1.8.0-openjdk
package:
  artifact: target/hello-dev.jar

functions:
  hello:
    handler: com.serverless.Handler
    events:
      - http:
          path: /
          method: get
